### ISSUE TITLE
Update config after install?

### ISSUE THREAD

**Issue by mihailstoynov** [aalaesar/install_nextcloud#71] opened 2019-08-14 11:20 UTC
I read somewhere in your documentation that you do not edit the configuration of nextcloud after initial install and checked that by changing the config and it didn't get updated.

Can you make your code update the config?

I don't see a reasonable case where someone would want to update the config manually.

**Comment by aalaesar** [comment] 2019-08-14 13:27
Hi
Thank you for your question.
This is a subject I have but some thought in it for quite some time.
The current code is quite old but It is in fact a limitation by design to keep the role indempotent. And do not break the app's configuration.

I would not have issue to use a template and use an yaml data structure if the config.php was only managed by ansible. But it's not the case: Nextcloud and some extra apps can add more entries in it, as the server is living it's life.
The risk of breaking something is big.  

There is possibly the use off the occ CLI to manage all the configuration. this whould be a very good alternative to templates but would require a lot of tasks to keep the role idempotent - but I haven't worked enough with it to see what's possible. -  
Probably making a custom module for the occ command would be the way to go.
It could allow to rewrite a lot of this role and go to V2 with new ones installation tasks and apps

**Comment by aalaesar** [comment] 2019-08-14 13:49
Sry wrong button.
After all those thoughts, what's blocking me to make the V2 happen is my lack of free time those past months

**Comment by mihailstoynov** [comment] 2019-08-22 22:10
The biggest issue that needs fixing is that when nextcloud updates it changes something in the config (redis had a tcp port, now it's a socket), or new nginx config, it's time consuming to fix.

occ would be a nice addition, I don't know how powerful it is. That won't work for nginx config though.

**Comment by aalaesar** [comment] 2019-08-23 14:24
Do you mean that currently, the role breaks nginx setup and then Nextcloud config when rerun ? 
On what distribution and version ?

**Comment by mihailstoynov** [comment] 2019-08-24 08:15
It doesn't break them on rerun.

But if the config file has updates when nextcloud updates, the role doesn't take that into account.
For example at some point redis was updated from listening on a tcp port to a socket. The nextcloud documentation reflected that. But since this role doesn't touch the documentation, it didn't fix it.

**Comment by aalaesar** [comment] 2019-08-24 11:05
Hard to standardise this kind of setup for various Nextcloud versions and distributions.

The role shouldn't run the configuration playbook if it detects Nextcloud as installed, unless modified, so it should not break any NC instance.  
 If the configuration has been updated by a upgrade, it should not be touched and you should not have corrective tasks to do after a run.
If you are in a multi instance installation scenario, you can adjust redis settings with variables. `nextcloud_redis_*`
By default the last version of the role use a socket to connect to redis. If the socket location has changed or is depending of the distribution please feel free to submit a fix with a PR. 🙂

**Comment by aalaesar** [comment] 2019-08-24 12:54
Just reread the whole issue and I understand what's you meant.  
I had misunderstood Nextcloud as the application while you meant the project, the configuration file as the Nextcloud app's _config.php_ while you meant the _web server's_ configuration.  

The subject of the issue is that the role doesn't follow closely Nextcloud releases and doesn't update quickly enough configuration changes that are hard coded in templates and tasks.

Well ... This requires continuous integration and testing to actively detect and fix changes. This is kind of overpowered for a single ansible role...
So the role is provided freely as best effort.

Do not hesitate to correct me

**Comment by mihailstoynov** [comment] 2019-08-26 17:20
I've been using your role since nextcloud 10 or 11, not sure. So my configuration was generated back then. And things change gradually, especially on major releases. And since the configuration is not touched by the role, sometimes something breaks.

What I was imaging as a solution is a heads-up message when something breaking might be released, like "double check redis configuration". And then I'll figure it out.

I guess a good approach is to check the release notes of nextcloud when a major version is released instead of insisting that the role check the configuration for issues that *might* arise.

This is in no way a critique of the role. I like this role a lot and it works pretty well. So you can close this issue.

**Comment by aalaesar** [comment] 2019-08-26 20:23
Yes the server configuration is an inconvenient for nginx as it doesn't use the .htaccess files edited by the project, all changes have to be reported on the template. 
I use nginx too on my setup.
Obviously the role whould requires myself to be more proactive about following Nextcloud RC schedules and update the role in advance...
I'll look on what can be done. 
I'm curious to know how you use the role to upgrade your Nextcloud instance

**Comment by mihailstoynov** [comment] 2019-08-28 08:54
I update via the occ. Can the role update? I haven't tried it.

Why don't you override the config.php file everytime? also the nginx config?

**Comment by aalaesar** [comment] 2019-08-28 09:41
> Can the role update? I haven't tried it.

No it purposely install only and skip the install if the application is already here so no upgrade. I made a upgrade role a while ago (nc 9 at the time) but the occ upgrade is much better now, so its kind of obsolete.

> Why don't you override the config.php file everytime? Isn't that the ansible way to do things?

Yes IF ansible is the only manager for the file. it's not the case for the config.php: it can be modified by occ  and nc applications
most of the time ansible managed files have a header warning "Ansible managed. do not edit".
It can't be applied here.

I'm now pretty convinced that occ is the way to go to, fully and indempotently, install and configure nextcloud.
I started working on custom module(s) to modify nexcloud configuration throught the occ cli
but i'm a noob in python and full dev so it might take some time.
I aim for a V2 of the role much more robust with  upgrade and configuration as code (yml)

**Comment by aalaesar** [comment] 2023-01-26 10:32
hello @mihailstoynov 
after v 2.0 is release future focus will be to develop a system_config module to use occ cli to apply configuration instead of templating the config file. This should allow users to use ansible to apply/update their config and maybe improve the role to run all installation tasks in an true indempotent fashion.
Closing this issue as the proposition is **accepted** and is now planned to be developed.
I'll open a new task/issue to follow development for this future module after 2.0 is realeased

**Closed by aalaesar** 2023-01-26 10:32 UTC
